### PR TITLE
add missing crypto import in signer.ts and update documentation

### PR DESCRIPTION
**Pull request by csteuer**
When trying to set up an app with the node example, I stumbled upon a few problems:
1. The example app and the snippet in the readme try to pass a `WebCryptoHmacSigner` object as a third argument to the `AppServer` constructor, but that constructor has only two arguments since 2ebbb1e
2. I got an error when installing the app:
    ```
    TypeError: Cannot read properties of undefined (reading 'subtle')
    ```
    Adding `import crypto from 'crypto'` to `signer.ts` resolved the issue.
3. The Shopware documentation uses a [different app-secret for testing and a different url-mapping](https://developer.shopware.com/docs/guides/plugins/apps/starter/starter-admin-extension.html). Having both in-sync makes it easier to get started with app development.

### CODE REVIEW

**Comment by shyim** [comment]
Which nodejs version are you using? 🤔

**Comment by csteuer** [comment]
> Which nodejs version are you using? 🤔

v18.16.0

**Comment by shyim** [comment]
I would say we should increase min node to 19. 
image


Importing crypto will break Deno and co. 😅

**Comment by csteuer** [comment]
That would work as well. Just tested it with v19.9.0

**Comment by shyim** [comment]
Thank you! :)

**Comment by shyim** [comment]
I added a hono example. Maybe a better start :)
https://github.com/FriendsOfShopware/app-server-sdk-js/commit/02c4e1fd08a02a1c526374ddc618e460083e2082

**Pull request merged**
